# Copyright 2024 Amazon.com, Inc. or its affiliates.

name: osml_tile_server_test
channels:
  - conda-forge
dependencies:
  - python=3.11
  - requests
  - boto3
  - numpy
  - conda-forge::proj=9.3.0
  - conda-forge::hilbertcurve
  - pip
  - pip:
    - locust
